# Generated by Django 4.2.7 on 2026-09-04 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('reminder_type', models.CharField(choices=[('VACCINATION', 'Vaccination'), ('DEWORMING', 'Deworming'), ('MEDICATION', 'Medication'), ('VET_APPOINTMENT', 'Vet Appointment'), ('GROOMING', 'Grooming'), ('DENTAL', 'Dental Checkup'), ('LICENSE', 'Pet License Renewal'), ('FLEA_TICK', 'Flea/Tick Treatment'), ('FEEDING', 'Feeding'), ('HEALTH_CHECKUP', 'Health Checkup'), ('CUSTOM', 'Custom')], default='CUSTOM', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('reminder_date', models.DateField()),
                ('reminder_time', models.TimeField(blank=True, null=True)),
                ('repeat_interval', models.IntegerField(default=0, help_text='Repeat every X days (0 = no repeat)')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('notify_by_email', models.BooleanField(default=False)),
                ('notify_by_sms', models.BooleanField(default=False)),
                ('notification_sent', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='pets.pet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reminder',
                'verbose_name_plural': 'Reminders',
                'db_table': 'reminders',
                'ordering': ['reminder_date', 'reminder_time'],
            },
        ),
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NOTIFICATION_SENT', 'Notification Sent'), ('REPEATED', 'Repeated')], max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='reminders.reminder')),
            ],
            options={
                'verbose_name': 'Reminder Log',
                'verbose_name_plural': 'Reminder Logs',
                'db_table': 'reminder_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
