# Generated by Django 4.2.7 on 2026-09-04 17:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=200)),
                ('vaccine_type', models.CharField(choices=[('CORE', 'Core Vaccine'), ('NON_CORE', 'Non-Core Vaccine'), ('RABIES', 'Rabies'), ('DHPP', 'DHPP (Distemper/Parvo)'), ('BORDETELLA', 'Bordetella'), ('LEPTOSPIROSIS', 'Leptospirosis'), ('LYME', 'Lyme Disease'), ('FELV', 'Feline Leukemia'), ('FVRCP', 'FVRCP (Feline Distemper)'), ('OTHER', 'Other')], default='CORE', max_length=20)),
                ('date_administered', models.DateField(default=django.utils.timezone.now)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('veterinarian', models.CharField(blank=True, max_length=100, null=True)),
                ('clinic_name', models.CharField(blank=True, max_length=200, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='vaccination_certificates/')),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('UPCOMING', 'Upcoming'), ('OVERDUE', 'Overdue')], default='UPCOMING', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='pets.pet')),
            ],
            options={
                'verbose_name': 'Vaccination',
                'verbose_name_plural': 'Vaccinations',
                'db_table': 'vaccinations',
                'ordering': ['-date_administered'],
            },
        ),
        migrations.CreateModel(
            name='VaccinationReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_date', models.DateField()),
                ('reminder_sent', models.BooleanField(default=False)),
                ('reminder_type', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('NOTIFICATION', 'Notification')], default='NOTIFICATION', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vaccination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reminder', to='medical.vaccination')),
            ],
            options={
                'db_table': 'vaccination_reminders',
            },
        ),
    ]
